version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/shell"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/shell/adapter"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/examples/simple-app"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
